/*Actions user*/
export const SET_DATA_PEOPLE = 'SET_DATA_PEOPLE'
export const ERROR_DATA_PEOPLE = 'ERROR_DATA_PEOPLE'
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE'
export const SET_SELECTED_FILM = 'SET_SELECTED_FILM'