/*Actions people*/
export const SET_DATA_PEOPLE = 'SET_DATA_PEOPLE'
export const ERROR_DATA_PEOPLE = 'ERROR_DATA_PEOPLE'
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE'
export const UPDATE_PAGE_PEOPLE_LIST = 'UPDATE_PAGE_PEOPLE_LIST'

/* Actions films */
export const SET_SELECTED_FILM = 'SET_SELECTED_FILM'
export const ERROR_DATA_FILM = 'ERROR_DATA_FILM'